../../src/ANISOFLOW 						\
-Input_type_gmtry 2 						\
-Input_file_gmtry grid.txt 					\
-Input_type_tplgy 0 						\
-Input_file_ppt o_aniso_properties.txt 		\
-Homogeneuos_ppt 							\
-Input_file_bc steady_bc.txt 				\
-Input_type_bc 2 							\
-Project_name 10x10_steady_o_aniso_traditional \
-Output_type 3 								\
-ksp_view_solution draw 					\
-draw_pause 5