BC: BC_generator.F90
	gfortran -g -O0 BC_generator.F90 -o BC_generator.exe
	rm ANISOFLOW_TEST.bc
	./BC_generator.exe

Tplgy: Tplgy_generator.F90
	gfortran Tplgy_generator.F90 -o Tplgy_generator.exe
	rm ANISOFLOW_TEST.tplgy
	./Tplgy_generator.exe