../../src/ANISOFLOW 						\
-Input_file_gmtry grid.txt 					\
-Input_type_tplgy 0 						\
-Input_file_ppt o_aniso_properties.txt 		\
-Homogeneuos_ppt 							\
-Input_file_bc bc.txt 						\
-Input_type_bc 2 							\
-Project_name 11x11_transitory_o_aniso_traditional \
-Run_options_time 1 						\
-Init_sol_value 10 							\
-ksp_view_solution draw 					\
-draw_pause 0.5